FROM python:3.12-slim

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8051

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]